INSERT INTO MANUFACTURE VALUES(1, 'HTC', 1);
INSERT INTO MANUFACTURE VALUES(2, 'Sony', 1);
INSERT INTO MANUFACTURE VALUES(3, 'Samsung', 1);
INSERT INTO MANUFACTURE VALUES(4, 'ZTE', 1);
INSERT INTO MANUFACTURE VALUES(5, 'Huawei', 1);
INSERT INTO MANUFACTURE VALUES(6, 'Xiaomi', 1);

-- HTC
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(1, 'C520E', '4.0', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(1, 'T328W', '4.0.4', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(1, 'T528T', '4.1.1', '3G,WIFI', 0, 1);
-- Sony
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(2, '22I', '2.3', 'WIFI', 0, 1);
-- Samsung
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(3, 'N7100', '4.3', '3G,4G,WIFI', 2.2, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(3, 'N9000', '4.2.2', '3G,4G,WIFI', 1.5, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(3, 'I9500', '4.3', '3G,WIFI', 1.5, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(3, 'I9300', '4.1', '3G,WIFI', 1.3, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(3, 'G7108V', '4.3', '3G,4G,WIFI', 0.5, 1);
-- ZTE
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(4, 'U930', '4.0', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(4, 'V889M', '4.0', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(4, 'V955', '4.0.4', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(4, 'U795', '4.0.4', '3G,WIFI', 0, 1);
-- Huawei
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(5, 'U8150', '2.3.7', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(5, 'U9508', '4.1', '3G,4G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(5, 'U8950D', '4', '3G,4G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(5, 'C8825D', '2.3', '3G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(5, 'G520', '4.1', '3G,4G,WIFI', 0, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(5, 'T8833', '4.1', '3G,WIFI', 0, 1);
-- Xiaomi
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(6, 'M3', '4.2', '3G,4G,WIFI', 2.5, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(6, '1S', '4.1', '3G,4G,WIFI', 2.1, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(6, 'M4', '4.4', '3G,4G,WIFI', 1.6, 1);
INSERT INTO MODEL(MANUFACTURE_ID, NAME, OS, NETWORK, OCCUPANCY, STATE) VALUES(6, '2S', '4.1.1', '3G,4G,WIFI', 1.6, 1);