-- ----------------------------
-- TABLE STRUCTURE FOR ACTION
-- ----------------------------
DROP TABLE IF EXISTS ACTION;
CREATE TABLE ACTION (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  TASK_ID INT(10) UNSIGNED NOT NULL,
  TYPE INT(10) UNSIGNED DEFAULT 1 COMMENT '1:NEW, 2:RETENTION',
  CONTENT LONGTEXT NOT NULL,
  TIME BIGINT(20) UNSIGNED NOT NULL,
  STATE INT(10) UNSIGNED NOT NULL DEFAULT 1 COMMENT '0:FALSE; 1:TRUE',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR AGENT
-- ----------------------------
DROP TABLE IF EXISTS AGENT;
CREATE TABLE AGENT (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  USES INTEGER DEFAULT 0 NOT NULL,
  TIME BIGINT(20) UNSIGNED DEFAULT NULL,
  LASTTIME BIGINT(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO AGENT VALUES ('100000', 0, 32489436216541, 32489436216541);

-- ----------------------------
-- TABLE STRUCTURE FOR AGENTRUNNER
-- ----------------------------
DROP TABLE IF EXISTS AGENTRUNNER;
CREATE TABLE AGENTRUNNER (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  SUBTASK_ID INT(10) UNSIGNED NOT NULL,
  AGENT_ID INT(10) UNSIGNED NOT NULL,
  PROXY_ID INT(10) UNSIGNED,
  ACTION_ID INT(10) UNSIGNED,
  DATE BIGINT(20) NOT NULL COMMENT '时间',
  ISRETENT INT(3) NOT NULL DEFAULT 0 COMMENT '留存情况，0：未留存；正数T：用户在第T日留存；负数T：临时状态，用户是第T日的留存用户',
  IMEI VARCHAR(20) DEFAULT NULL COMMENT 'IMEI',
  SN VARCHAR(20) DEFAULT NULL COMMENT '序列号',
  MAC VARCHAR(20) DEFAULT NULL COMMENT 'MAC地址',
  ANDROIDID VARCHAR(20) DEFAULT NULL COMMENT 'ANDROID ID',
  MANUFACTURE VARCHAR(20) DEFAULT NULL COMMENT 'MANUFACTURE',
  MODEL VARCHAR(20) DEFAULT NULL COMMENT 'MODEL',
  OS VARCHAR(10) DEFAULT NULL COMMENT '操作系统版本号',
  NETWORK VARCHAR(50) DEFAULT NULL COMMENT '网络，枚举值为：3G、4G和WIFI',
  MOBILE VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  STATE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0:START; 1:RUNNING; 2:END; 9:EXCEPTION',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR APPLICATION
-- ----------------------------
DROP TABLE IF EXISTS APPLICATION;
CREATE TABLE APPLICATION (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PID INT(10) UNSIGNED DEFAULT 0,
  MD5 VARCHAR(128) NOT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  ALIASNAME VARCHAR(500) DEFAULT NULL,
  SIZE BIGINT(20) UNSIGNED DEFAULT NULL,
  PACKAGENAME VARCHAR(100) DEFAULT NULL,
  VERSION VARCHAR(20) DEFAULT NULL,
  OS VARCHAR(20) DEFAULT NULL,
  STARTACTIVITY VARCHAR(200) DEFAULT NULL,
  ICON BLOB,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR INSTALLATION
-- ----------------------------
DROP TABLE IF EXISTS INSTALLATION;
CREATE TABLE INSTALLATION (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  DISPATCHER_ID INT(10) UNSIGNED NOT NULL,
  SN VARCHAR(50) DEFAULT NULL,
  RESULT VARCHAR(255) DEFAULT NULL,
  STATE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0:START; 1:RUNNING; 2:END; 9:EXCEPTION',
  TIME BIGINT(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR SERVER
-- ----------------------------
DROP TABLE IF EXISTS SERVER;
CREATE TABLE SERVER (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  URL VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO SERVER(URL) VALUES('http://localhost:8080/ast/');

-- ----------------------------
-- TABLE STRUCTURE FOR DISPATCHER
-- ----------------------------
DROP TABLE IF EXISTS DISPATCHER;
CREATE TABLE DISPATCHER (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  TASK_ID INT(10) UNSIGNED NOT NULL,
  SERVER_ID INT(10) UNSIGNED NOT NULL,
  RESULT VARCHAR(255) DEFAULT NULL,
  CODE INT(10) UNSIGNED DEFAULT NULL,
  STATE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0:START; 1:RUNNING; 2:END; 9:EXCEPTION',
  TIME BIGINT(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR SUBTASK
-- ----------------------------
DROP TABLE IF EXISTS SUBTASK;
CREATE TABLE SUBTASK (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  TASK_ID INT(10) UNSIGNED NOT NULL,
  PERCENT INT(10) UNSIGNED NOT NULL COMMENT '用户占比',
  USERS INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '新增用户数',
  SILENT_USERS INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '静默用户数',
  USERS_DONE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '完成用户数',
  DR_USERS INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '日留存用户数',
  DR_DONE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '日留存完成用户数',
  WR_USERS INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '周留存用户数',
  WR_DONE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '周留存完成用户数',
  MR_USERS INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '月留存用户数',
  MR_DONE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '月留存完成用户数',
  START_DATE BIGINT(20) NOT NULL COMMENT '开始时间段',
  END_DATE BIGINT(20) NOT NULL COMMENT '结束时间段',
  TOTAL INT(10) UNSIGNED NOT NULL COMMENT '预测测试次数',
  ACTUAL INT(10) UNSIGNED NOT NULL COMMENT '实际测试次数',
  RUNNING INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PASS INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ERROR INT(10) UNSIGNED NOT NULL DEFAULT 0,
  STATE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0:START; 1:RUNNING; 2:END; 9:EXCEPTION',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR TASK
-- ----------------------------
DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INT(10) UNSIGNED NOT NULL,
  APPLICATION_ID INT(10) UNSIGNED NOT NULL,
  USERS INT(10) UNSIGNED NOT NULL COMMENT '每日新增用户数',
  CONVERSION INT(10) UNSIGNED NOT NULL COMMENT '转化率',
  DAY_RETENTION INT(10) UNSIGNED NOT NULL COMMENT '日留存率',
  WEEK_RETENTION INT(10) UNSIGNED NOT NULL COMMENT '周留存率',
  MONTH_RETENTION INT(10) UNSIGNED NOT NULL COMMENT '月留存率',
  DISTRICT VARCHAR(200) NOT NULL COMMENT '地域列表，以,分隔',
  START_DATE BIGINT(20) NOT NULL COMMENT '开始日期',
  END_DATE BIGINT(20) NOT NULL COMMENT '结束日期',
  TOTAL INT(10) UNSIGNED NOT NULL COMMENT '预测测试次数',
  ACTUAL INT(10) UNSIGNED NOT NULL COMMENT '实际测试次数',
  PASS INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ERROR INT(10) UNSIGNED NOT NULL DEFAULT 0,
  TIME BIGINT(20) UNSIGNED DEFAULT NULL,
  STATE INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0:START; 1:RUNNING; 2:END; 9:EXCEPTION',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR USER
-- ----------------------------
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(20) NOT NULL,
  NICKNAME VARCHAR(20) DEFAULT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PHONE VARCHAR(20) DEFAULT NULL,
  ASSETS INT(10) UNSIGNED DEFAULT 0,
  STATE INT(10) UNSIGNED DEFAULT 1 COMMENT '0:UNACTIVED; 1:NORMAL; ',
  ROLE INT(10) UNSIGNED DEFAULT 1 COMMENT '0:ADMIN; 1:USER',
  PRIMARY KEY (ID)
) ENGINE=INNODB AUTO_INCREMENT=1000002 DEFAULT CHARSET=UTF8;

-- ----------------------------
-- RECORDS OF USER
-- ----------------------------
INSERT INTO USER VALUES ('1000000', 'admin', 'admin', '4297F44B13955235245B2497399D7A93', 'admin@ast.com', '(+86)13866666666', '900', '1', '0');
INSERT INTO USER VALUES ('1000001', 'molab', 'molab', '4297F44B13955235245B2497399D7A93', 'molab@ast.com', '(+86)13866666666', '900', '1', '1');

-- ----------------------------
-- TABLE STRUCTURE FOR PROXY
-- ----------------------------
DROP TABLE IF EXISTS PROXY;
CREATE TABLE PROXY (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  IP VARCHAR(50) NOT NULL,
  PORT INT(10) NOT NULL,
  DISTRICT_CODE INT(3) NOT NULL COMMENT '地域编码',
  DISTRICT_NAME VARCHAR(10) DEFAULT NULL COMMENT '地域名称',
  ISUSED INT(3) NOT NULL DEFAULT 0 COMMENT '是否已使用，0:FALSE; 1:TRUE',
  TIME BIGINT(20) UNSIGNED NOT NULL COMMENT '收录时间',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR MANUFACTURE
-- ----------------------------
DROP TABLE IF EXISTS MANUFACTURE;
CREATE TABLE MANUFACTURE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	STATE INT(10) UNSIGNED DEFAULT 1 COMMENT '0:FALSE; 1:TRUE;',
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR MODEL
-- ----------------------------
DROP TABLE IF EXISTS MODEL;
CREATE TABLE MODEL (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	MANUFACTURE_ID INTEGER UNSIGNED NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	OS VARCHAR(10) NOT NULL,
	NETWORK VARCHAR(50) NOT NULL,
	OCCUPANCY FLOAT COMMENT '市场占有率',
	STATE INT(10) UNSIGNED DEFAULT 1 COMMENT '0:FALSE; 1:TRUE;',
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- ----------------------------
-- TABLE STRUCTURE FOR DISTRICT
-- ----------------------------
DROP TABLE IF EXISTS DISTRICT;
CREATE TABLE DISTRICT (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	CODE INTEGER UNSIGNED NOT NULL COMMENT '省份编码',
	NAME VARCHAR(10) NOT NULL COMMENT '省份名称',
	SHORT VARCHAR(10) COMMENT '省份简称，拼音',
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;